# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "common.yml"
  end

  config.vm.define "master", primary: true do |s|
    s.vm.network :private_network, :ip => "10.42.0.10"
    config.vm.provision "ansible" do |ansible1|
      ansible1.playbook = "master.yml"
    end
  end

  config.vm.define "slave" do |c|
    c.vm.network :private_network, :ip => "10.42.0.15"
    config.vm.provision "ansible" do |ansible2|
      ansible2.playbook = "slave.yml"
    end
  end

end
